repos:
- hooks:
  - {id: check-yaml}
  - {id: end-of-file-fixer}
  - {id: trailing-whitespace}
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
- hooks:
  - entry: poetry run summon lint --no-full-report
    id: linters
    language: system
    name: Lint
    require_serial: true
    types: [python]
  - entry: poetry run summon format
    id: formatters
    language: system
    name: Format
    types: [python]
  repo: local
